name: Remindme CI
on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Copy .env.example to .env
      working-directory: src
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install composer dependencies
      working-directory: src
      run: composer install
    - name: Set required directory permissions
      working-directory: src
      run: chmod -R 777 storage bootstrap/cache
    - name: Generate encryption key
      working-directory: src
      run: php artisan key:generate
    - name: Create temporary sqlite database
      working-directory: src
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Run laravel database migrations
      working-directory: src
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --force
    - name: Run unit tests via PHPUnit
      working-directory: src
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

  laravel-build-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM dependencies
        working-directory: src
        run: npm install
      - name: Build assets
        working-directory: src
        run: npm run build